name:       CSVQL
version:    0.1.0.0
github:     "githubuser/CSVQL"
license:    BSD-3-Clause
author:     "Group 26"
maintainer: "mw5g23@soton.ac.uk"
copyright:  "University Of Southampton"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: Alex and Happy project.

dependencies:
- directory
- base >= 4.7 && < 5
- array


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  CSVQL-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSVQL

tests:
  CSVQL-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSVQL
